version: '3.8'

services:
  api:
    container_name: gleanr-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api/src:/app/src
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    env_file:
      - .env
    networks:
      - gleanr_network
    depends_on:
      - db
    restart: on-failure

  client:
    container_name: gleanr-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - VITE_DEV_SERVER_HOST=0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - gleanr_network

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - gleanr_network

volumes:
  db_data:

networks:
  gleanr_network: