version: '3.8'

services:
  api:
    container_name: gleanr-api
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api/src:/app/src
    environment:
      - ENVIRONMENT=development

  client:
    container_name: gleanr-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - VITE_DEV_SERVER_HOST=0.0.0.0
    stdin_open: true
    tty: true
    depends_on:
      - api